### ISSUE TITLE
[epic] Improve CKAN <=> Frictionless conversion (June 2020)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionless-ckan-mapper#15]
Improve existing converter and especially the docs.

Existing converter: https://github.com/frictionlessdata/ckan-datapackage-tools

## Job Stories

Job story: When getting data in and out of CKAN I'm frequently using Frictionless formats and tools (its my default format for extraction from other systems) and I want to be able to do conversion to and from CKAN metadata structure so that I can do my work quickly and without having to dig through CKAN documentation.

Bigger context: frequently pulling data from other systems into CKAN -- and from CKAN into other systems. We want to use Frictionless as the intermediate format so we can convert MxN into M+N problem.

## Acceptance

* [x] Documentation  of CKAN metadata (e.g. in a spreadsheet) **DONE CKAN entities https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=1925460244*
* [x] Mapping against Frictionless specs **DONE - mappings added to the sheet in previous item**
* [ ] Page / docs on website (reference?)
* [x] Scripts / tooling for doing this -- **Done:** PR #36 addresses the final touches to the `Makefile`, which facilitates all this and is also integrated to Travis.
* [x] Release to pypi -- **Done:** Everything is ready after merging #36. More discussion in #18.

## Tasks

* [x] Do the analysis
* [x] README driven development #13 
  * [x] Install / usage
  * [x] Quick start
  * [x] Reference
* [x] Implement CKAN => Frictionless #19
* [x] Implement Frictionless => CKAN #21
* [x] Update README -- **Done:** PR #35 merged.
* [x] Release to PyPI -- **Done:** Everything is ready after merging #36. More discussion in #18.

### Analysis of CKAN mapping

* [x] List CKAN metadata in spreadsheet https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=0
  * [x] Package https://github.com/ckan/ckan/blob/master/ckan/model/package.py
  * [x] Resource https://github.com/ckan/ckan/blob/master/ckan/model/resource.py 
  * [ ] Data Dictionary TODO
  * [ ] ❓ (Future) Brief comparison against package_show (which has much more)
* [x] Algorithm for CKAN <=> Frictionless
  * [x] Basic mapping of metadata
  * [x] Written out algorithm

## Analysis

```
Frictionless   <=>     CKAN
---------------------------
Data Package  <=>   Package (Dataset)
Data Resource <=>   Resource
Table Schema  <=>   Data Dictionary?? (datastore resources can have schemas)
```

Example standalone script https://gist.github.com/rufuspollock/bd8ae3575950d180cce33da59c021299

**Comment by AyrtonB** [comment]
Thanks, this is really useful. I was wondering whether the Data Dictionary is still planned to be integrated? And if so whether that would enable a full round trip between FD to CKAN conversions?

**Comment by rufuspollock** [comment]
@AyrtonB you can already do a full roundtrip and we tested that quite a bit.

Re data dictionary: CKAN doesn't really use a data dictionary so that why it wasn't done - you sort of have that in the datastore but not really.

**Comment by rufuspollock** [comment]
FIXED. This was all done!

**Comment by rufuspollock** [comment]
@AyrtonB by the data dictionary i mean something like "table schema" which CKAN doesn't have a specific field for on resources. The way this works now is we do store the table schema (data dictionary) into a field called `schema` on resources and then round trip that back if it exists.

**Comment by AyrtonB** [comment]
That makes a lot of sense, thank you for clarifying. I will have a go parsing the table schema data from the HTML of the data dictionary (from the datastore) but will probably settle on using the approach you've described.

Is there an example CKAN dataset with the schema field completed?

**Comment by rufuspollock** [comment]
@AyrtonB i don't know of a nice example dataset with the schema field in the datastore but you can read the docs and make one up - PS: if you do do this a pull request adding info to the docs here would be useful (maybe even some sample code!)

**Comment by AyrtonB** [comment]
@rufuspollock, thanks, will do!
