### ISSUE TITLE
Rename repo and package to frictionless-ckan-mapper

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionless-ckan-mapper#18]
Why?

* Frictionless is our naming focus (not Data Package)
* More clearly says what it does (it's not general tooling: it's just a mapper)

(Why not: it's a hassle)

## Tasks

* [x] Change repo name on github
* [x] Change python package name in repo
* [x] Push to PyPi  -- **Done**: https://pypi.org/project/frictionless-ckan-mapper/
* [x] Fix on coveralls and in badge in README -- **DONE**: It shows correctly in the README.

**Comment by sglavoie** [comment]
* `coveralls` is now configured and submitting PRs/commits triggers the coverage, which is now being reported.
* PR #36 should be what's required to get going on releasing to PyPi.
  * We should update the README before the release (see PR #35).
  * I suspect we can consider PR #34: it's not perfect, but it won't break anything either.

**Comment by sglavoie** [comment]
**FIXED**: Closing because everything has been done. All the necessary PRs were merged and the package is live at https://pypi.org/project/frictionless-ckan-mapper/.
