### ISSUE TITLE
Refactor and improve CKAN => Frictionless Code and tests

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/frictionless-ckan-mapper#19]
We want to refactor and improve CKAN => Frictionless code e.g.

* Extras handling including parsing of JSON values e.g. schema
* Full set of mappings

Approach: *no* changes wherever possible so we support roundtripping. Add option to "enforce" more compatibility eg. name getting slugified on resource etc.

Also option for "generous" e.g. name => title on a resource.

## Tasks

Design algorithm => incrementally implement based on tests

* [x] Design algorithm and document in docstring **See `ckan_to_frictionless.py`**
* [x] Migrate existing tests and have them pass
  * [x] list existing tests
* [x] Refactor Resource stuff
  * [x] Dedupe simple pass through tests e.g. for Resource description, hash etc (which just pass through)
  * [x] ~~run off json fixtures as much as possible (this is both easier to understand and means we can reuse for javascript code)~~ FUTURE
  * [x] ~~Come up with a fixtures naming pattern~~
  * [x] Add tests based on our detailed mapping analysis in spreadsheet https://docs.google.com/spreadsheets/d/1XdqGTFni5Jfs8AMbcbfsP7m11h9mOHS0eDtUZtqGVSg/edit#gid=2099009729 **DONE for resource**
* [x] Refactor Dataset/Package mapping
  * [x] keys_are_removed_that_should_be -- **DONE**: See https://github.com/frictionlessdata/frictionless-ckan-mapper/commit/ddc930922f8f4e0a31782e5709311ce35558f2f3
  * [x] extras_expanded
  * [x] unjsonify_values -- **DONE**: See https://github.com/frictionlessdata/frictionless-ckan-mapper/pull/25
  * [x] license_is_converted
  * [x] author_is_converted
  * [x] ~~sources_is_converted~~ sources does not exist in CKAN
  * [x] keys_are_passed_through -- **DONE**: See https://github.com/frictionlessdata/frictionless-ckan-mapper/pull/27
  * [x] resources_are_converted: length check and one check on one resource -- **DONE**: See https://github.com/frictionlessdata/frictionless-ckan-mapper/pull/23 and https://github.com/frictionlessdata/frictionless-ckan-mapper/pull/24 for more details (both are now merged).
  * [x] null_values_are_removed -- **In Progress**: Ready to merge → https://github.com/frictionlessdata/frictionless-ckan-mapper/pull/26
* [x] ~~Add instructions for adding tests in future~~ Obvious from code style / structure

### Existing tests

```
Dataset

test_basic_dataset_in_setup_is_valid       # can drop probably
test_dataset_author_and_source
test_dataset_ckan_url
test_dataset_extras
test_dataset_license
test_dataset_maintainer
test_dataset_name_title_and_version
test_dataset_notes
test_dataset_only_requires_a_name_to_be_valid
test_dataset_tags

Resource

test_resource_description
test_resource_format
test_resource_hash
test_resource_name_converts_unicode_characters
test_resource_name_lowercases_the_name
test_resource_name_slugifies_the_name
test_resource_path_is_set_even_for_uploaded_resources
test_resource_schema
test_resource_schema_string
test_resource_schema_url
test_resource_url
```

**Comment by rufuspollock** [comment]
FIXED. All done 🎉
