### ISSUE TITLE
 CKAN => FD issues re bytes, id, empty tags

### ISSUE THREAD

**Issue by sglavoie** [frictionlessdata/frictionless-ckan-mapper#33]
When I convert a CKAN dataset to a Frictionless package and then a Frictionless package to a CKAN dataset again, I expect the mapping to be coherent and remap from Frictionless to CKAN what is necessary so I can use this converted CKAN dataset as if it were the original dataset or as close to it as possible. Possible issues noted:

* Frictionless resource has `bytes` key and it is not being converted when inside a dataset. **FIXED in cf9e424d929631db6b293c889edb08ca3106196a**
* If a CKAN package has the `id` key, this key is stored in `extras` in a Frictionless package (this is OK) but stays in `extras` when converting again to a CKAN package. Doesn't CKAN need to identify a package with an `id`? It could be retrieved from `extras` in strict mode. **FIXED in b6feb949c3b4f1d579a14231674332c29643b003**
* Having no "tags" in CKAN creates the new key/value pair `"keywords": []` when doing a round trip (the new converted CKAN dataset has a `keywords` key it didn't have before and it's empty). Maybe we could check against empty lists and dictionaries to make sure we do not copy those over (as they are basically equivalent to `null`), especially when it's not a key recognized by CKAN (`keywords` is specific to Frictionless)? **FIXED in b2de64c9a376f75e6c9bf8b18293fe30cf3e30bf**

## Acceptance

* [ ] Mappings from CKAN => FD => CKAN are consistent and produce the expected results.

## Tasks

* [ ] Make sure that everything that is being remapped from CKAN to Frictionless is also remapped correctly from Frictionless to CKAN.
  * [x] Make sure that all the properties in a CKAN resources are named correctly (e.g. "size" and "bytes").

**Comment by rufuspollock** [comment]
@sglavoie i don't get why this is happening:

> Inside a CKAN resource, we have the size key. When we do a round trip when converting a package, this key is mapped to bytes instead of size (because of the Frictionless conversion).

This is a bug 🐛  Can you look at fixing this.

**Comment by pdelboca** [comment]
When doing a round tripping, if I add a **tag** to the package in CKAN the result of `package_show` is the following one:

```
 'tags': [{'display_name': u'FancyTag',
           'id': u'b273a236-e4f8-498b-a64c-fc8f10384afd',
           'name': u'FancyTag',
           'state': u'active',
           'vocabulary_id': None},
          {'display_name': u'NewFancyTag',
           'id': u'8d9e96e0-cf58-44e1-90eb-1b34f778f442',
           'name': u'NewFancyTag',
           'state': u'active',
           'vocabulary_id': None}],
```

However, the library is only mapping the name of the tag:
```
 'keywords': [u'FancyTag', u'NewFancyTag'],
```

So if I do a reconversion using `ftc.package()` it will return:
```
'tags': [{'name': u'FancyTag'}, {'name': u'NewFancyTag'}],
```

Which is missing `id`, `display_name`, `state` and `vocabulary_id`.

**Comment by sglavoie** [comment]
@rufuspollock:

* Fix _Having no "tags" in CKAN creates the new key/value pair `"keywords": []`_ in PR #40 
* Fix _Inside a CKAN resource, we have the `size` key. When we do a round trip when converting a package, this key is mapped to `bytes` instead of `size` (because of the Frictionless conversion)_ in PR #41 

**TODO**:

* Define expected behavior for remapping `tags`/`keywords` with @pdelboca and submit relevant PR for that.

**Comment by rufuspollock** [comment]
FIXED. All items done (see description).
